---

- name: Group membership validity check - testing|development|production servers
  assert:
    that:
        - '"servers_testing" in group_names or "servers_development" in group_names or "servers_production" in group_names'
        - 'not "servers_demo" in group_names or ("servers_demo" in group_names and not ("servers_development" in group_names or "servers_production" in group_names))'
        - 'not "servers_development" in group_names or ("servers_development" in group_names and not ("servers_demo" in group_names or "servers_production" in group_names))'
        - 'not "servers_production" in group_names or ("servers_production" in group_names and not ("servers_demo" in group_names or "servers_development" in group_names))'
    msg: "Server must be member of exactly one of the 'servers_demo', 'servers_development', 'servers_production' groups"
