---

- name: Configuring Nagios monitoring
  template:
    src: "{{ item }}"
    dest: /etc/nagios/nrpe.d/mentat.cfg
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "host_files/{{ inventory_hostname }}/nrpe_mentat.cfg.j2"
    - "group_files/servers-production/nrpe_mentat.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-production/nrpe_mentat.cfg.j2"
    - "group_files/servers-development/nrpe_mentat.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-development/nrpe_mentat.cfg.j2"
    - "group_files/servers-demo/nrpe_mentat.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-demo/nrpe_mentat.cfg.j2"
    - "group_files/servers/nrpe_mentat.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers/nrpe_mentat.cfg.j2"
    - "nrpe_mentat.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "nrpe_mentat.cfg.j2"
  notify: Restart NRPE service
  when: '"servers-monitored" in group_names'

- name: Configuring system status script
  template:
    src: "{{ item }}"
    dest: /opt/system-status/system-status.d/40-mentat
    owner: root
    group: root
    mode: 0755
  with_first_found:
    - "host_files/{{ inventory_hostname }}/system-status-mentat.j2"
    - "group_files/servers-production/system-status-mentat.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-production/system-status-mentat.j2"
    - "group_files/servers-development/system-status-mentat.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-development/system-status-mentat.j2"
    - "group_files/servers-demo/system-status-mentat.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers-demo/system-status-mentat.j2"
    - "group_files/servers/system-status-mentat.{{ ansible_lsb['codename'] }}.j2"
    - "group_files/servers/system-status-mentat.j2"
    - "system-status-mentat.{{ ansible_lsb['codename'] }}.j2"
    - "system-status-mentat.j2"
  when: '"servers-commonenv" in group_names'

- name: Creating required databases
  shell: /etc/mentat/scripts/sqldb-init.sh && touch /etc/mentat/ansible/sqldb-init.sh.mark
  args:
    creates: /etc/mentat/ansible/sqldb-init.sh.mark

- name: Creating database schemas and indices
  shell: /usr/local/bin/mentat-dbmngr.py --command init && touch /etc/mentat/ansible/mentat-dbmngr.py.mark
  args:
    creates: /etc/mentat/ansible/mentat-dbmngr.py.mark

- name: Stamping main database to latest migration revision
  shell: hawat-cli db stamp head && touch /etc/mentat/ansible/hawat-cli-stamp-head.mark
  args:
    creates: /etc/mentat/ansible/hawat-cli-stamp-head.mark

- name: Stamping event database to latest migration revision
  shell: /etc/mentat/scripts/sqldb-migrate.sh stamp head && touch /etc/mentat/ansible/sqldb-stamp-head.mark
  args:
    creates: /etc/mentat/ansible/sqldb-stamp-head.mark

- name: Precaching database enumerations and dictionaries
  shell: /usr/local/bin/mentat-precache.py --allow-empty && touch /etc/mentat/ansible/mentat-precache.py.mark
  args:
    creates: /etc/mentat/ansible/mentat-precache.py.mark

- name: Start Mentat real-time message processing modules
  shell: /usr/local/bin/mentat-controller.py --command=start
  register: mentat_start_result
  changed_when: "'Launching module' in mentat_start_result.stdout"

- name: Enable Mentat post-processing modules
  shell: /usr/local/bin/mentat-controller.py --command=enable
  register: mentat_enable_result
  changed_when: "'Enabling module' in mentat_enable_result.stdout"

- name: Ensuring Mentat system is enabled at system start
  service:
    name: mentat
    enabled: yes
